backend:
  name: git-gateway
  branch: main

media_folder: "assets/img" # Folder tempat gambar tersimpan
public_folder: "/assets/img"

collections:
  - name: "manual_pages"
    label: "Isi Manual Book (Per Bagian)"
    files:
      - label: "Adm Kredit"
        name: "adm_kredit"
        file: "pages/adm_kredit.html"
        fields:
          - {label: "Judul Halaman", name: "title", widget: "string"}
          - {label: "Gambar Unggulan", name: "image", widget: "image"}
          - {label: "Konten Panduan", name: "body", widget: "markdown"}

      - label: "Analis"
        name: "analis"
        file: "pages/analis.html"
        fields:
          - {label: "Judul Halaman", name: "title", widget: "string"}
          - {label: "Gambar Unggulan", name: "image", widget: "image"}
          - {label: "Konten Panduan", name: "body", widget: "markdown"}

      - label: "Audit"
        name: "audit"
        file: "pages/audit.html"
        fields:
          - {label: "Judul Halaman", name: "title", widget: "string"}
          - {label: "Gambar Unggulan", name: "image", widget: "image"}
          - {label: "Konten Panduan", name: "body", widget: "markdown"}

      - label: "Kasir"
        name: "kasir"
        file: "pages/kasir.html"
        fields:
          - {label: "Judul Halaman", name: "title", widget: "string"}
          - {label: "Gambar Unggulan", name: "image", widget: "image"}
          - {label: "Konten Panduan", name: "body", widget: "markdown"}

      # Kamu bisa menambah role lain (Tabungan, Keuangan, dll) dengan pola yang sama di sini
