backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "panduan"
    label: "Update Isi Manual Book"
    folder: "content" # CMS akan membaca semua file di folder ini
    extension: "md"
    format: "frontmatter"
    create: true # Bisa buat file baru
    editor:
      preview: true # Memastikan fitur preview aktif
    slug: "{{slug}}"
    fields:
      - {label: "Judul Halaman", name: "title", widget: "string"}
      - {label: "Gambar Utama", name: "image", widget: "image", required: false}
      - {label: "Isi Panduan", name: "body", widget: "markdown"}
