backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "panduan"
    label: "Update Isi Manual Book"
    folder: "content" # Kita pindah ke folder khusus konten
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID Bagian", name: "id_bagian", widget: "select", options: ["adm_kredit", "analis", "audit", "kasir", "tabungan"]}
      - {label: "Judul Panduan", name: "title", widget: "string"}
      - {label: "Gambar Dokumentasi", name: "image", widget: "image", required: false}
      - {label: "Isi Panduan", name: "body", widget: "markdown"}
